### ISSUE TITLE
VS2019 Can't see code previewer 

### ISSUE THREAD

**Issue by bogdan-lopatkin** [UXDivers/Gorilla-Player-Beta-Bugs-1.0.0#360]
Hello everybody,
I have a problem with Gorilla, I see the gorilla picture in the right corner of my xaml file, Gorilla is connected, I can see the xaml path in the Gorilla player status but I don't see the preview. 
Do I miss something?

![goriila2](https://user-images.githubusercontent.com/52372518/63223072-dac50900-c1b8-11e9-9e4b-cae8c86a8278.png)
![goriila3](https://user-images.githubusercontent.com/52372518/63223073-dac50900-c1b8-11e9-9b67-bb8bf7593dfa.png)
![goriila](https://user-images.githubusercontent.com/52372518/63223075-dac50900-c1b8-11e9-9f60-49abb6682426.png)

**Comment by LeoHere** [comment]
@OverWoob the only missing thing piece there seems to be the previewer app. The actual previewing happens in an app hosting Gorilla SDK running in the simulator or real device.

Please see [this blog](https://devblogs.microsoft.com/xamarin/gorilla-player-a-tool-to-craft-beautiful-xaml-uis-for-xamarin-forms/) post for more information.

**Comment by LeoHere** [comment]
Closing the issue now. Feel free to open it again if you need to.
