### ISSUE TITLE
Gorilla Player Solution Is not Proper

### ISSUE THREAD

**Issue by ankurpathak** [UXDivers/Gorilla-Player-Beta-Bugs-1.0.0#362]
I opened Gorilla Player Solution 1.5.3 in Visual Studio 2019 to install it in my device.
But its giving error. It can't find NuGet Package for Gorilla Version 1.5.3.

**Comment by LeoHere** [comment]
@ankurpathak please try again. Nuget 1.5.3 was not up at that time. 

Closing the issue now. Feel free to open it again if you need to.
