### ISSUE TITLE
"Number of parameters specified does not match the expected number.","ExceptionType":"System.Reflection.TargetParameterCountException"

### ISSUE THREAD

**Issue by taieb1919** [UXDivers/Gorilla-Player-Beta-Bugs-1.0.0#365]
i have test a simple content page with  Gorilla player 1.5.2
but i have this Exception message:

``

Error
`"Context":"XAML: Number of parameters specified does not match the expected number.","ExceptionMessage":"Number of parameters specified does not match the expected number.","ExceptionType":"System.Reflection.TargetParameterCountException","ExceptionStackTrace":"  at System.Reflection.MonoMethod.ConvertValues (System.Reflection.Binder binder, System.Object[] args, System.Reflection.ParameterInfo[] pinfo, System.Globalization.CultureInfo culture, System.Reflection.BindingFlags invokeAttr) [0x00016] in <d4a23bbd2f544c30a48c44dd622ce09f>:0 \n  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00011] in <d4a23bbd2f544c30a48c44dd622ce09f>:0 \n  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <d4a23bbd2f544c30a48c44dd622ce09f>:0 \n  at UXDivers.Gorilla.Platform.XamlLoader+<>c__DisplayClass1_0.<.cctor>b__2 (System.Object view, System.String xaml) [0x00000] in <f4ac2943b064459a90a07741c30cd33a>:0 \n  at UXDivers.Gorilla.Platform.XamlLoader.LoadFromXaml[TView] (TView view, System.String xaml) [0x00000] in <f4ac2943b064459a90a07741c30cd33a>:0 \n  at UXDivers.Gorilla.PageBuilder.CreatePage (UXDivers.Gorilla.PageBuilder+TypeInfo rootType, System.String xaml) [0x0011e] in <25d52da819b3416ebc198d830ac32efc>:0 \n  at UXDivers.Gorilla.PageBuilder.BuildXamlPage (System.String xaml, UXDivers.Gorilla.ErrorTracker issueTracker) [0x00020] in <25d52da819b3416ebc198d830ac32efc>:0 \n  at UXDivers.Gorilla.Coordinator.ProcessTargetUpdate (UXDivers.Gorilla.UpdatePayload payload) [0x0026d] in <25d52da819b3416ebc198d830ac32efc>:0 ","NonExceptionType":null,"IsTerminating":false,"level":"error","message":"Client reported error","timestamp":"2019-10-22T13:30:58.742Z"}
`

i've cleaned all project 
Enabled/disabled Linker 
enabled/disabled  AOT....
but still have this message

**Comment by truekxmexico** [comment]
i have the same problem...

**Comment by Bohirjon** [comment]
Make sure the Gorilla server has the same version 1.5.2.

**Comment by taieb1919** [comment]
Have the same gorilla server

**Comment by Bohirjon** [comment]
I got it working back downgrading the nuget xamarin.forms. I had created a issue for that [issue 366](https://github.com/UXDivers/Gorilla-Player-Support/issues/366)

**Comment by taieb1919** [comment]
After DownGrading Xamarin.forms, I was able to work with gorilla player .
thank you @Bohirjon .

**Comment by LeoHere** [comment]
@taieb1919 @Bohirjon please migrate to 1.5.4 to fix the issue with the latest version of Xamarin Forms. You can download the installers from [here](https://github.com/UXDivers/Gorilla-Player-Support/releases/tag/v1.5.4.0).

**Comment by rubgithub** [comment]
Jesus! each error has one version different to fix!

![image](https://user-images.githubusercontent.com/3399476/70325309-13402f80-1808-11ea-992e-5229d8e1f1a2.png)
