### ISSUE TITLE
Cannot read property 'tagReplacement' of null

### ISSUE THREAD

**Issue by pzavala26** [UXDivers/Gorilla-Player-Beta-Bugs-1.0.0#367]
I can't get the new gorilla player 1.5.4 works, i get error to display page preview

Error occurred while loading C:\Test\ExamplePage.xaml (error message: Cannot read property 'tagReplacement' of null)

I try this:

'default'
UXDivers.GorillaPlayer.SDK - 1.5.4
Xamarin.Android.Support.* - 27.0.2
Xamarin.Forms - 3.2.0.839982

UXDivers.GorillaPlayer.SDK - 1.5.4
Xamarin.Android.Support.* - 28.0.0.1
Xamarin.Forms - 4.2.0.778463

suppesed will work in this fix but not
UXDivers.GorillaPlayer.SDK - 1.5.4
Xamarin.Android.Support.* - 28.0.0.3
Xamarin.Forms - 4.3.0.908675 

Only this works
UXDivers.GorillaPlayer.SDK - 1.5.3
Xamarin.Android.Support.* - 28.0.0.3
Xamarin.Forms - 4.2.0.910310

**Comment by edimaulana** [comment]
i have same problem

**Comment by darthza** [comment]
same problem

**Comment by LeoHere** [comment]
@pzavala26 @edimaulana @darthza this issue should be fixed in 1.5.5. Please download it from [here](https://drive.google.com/drive/folders/1QcLKRl3xwwfa5HLCHQwLQs1aSn3iNEfl?usp=sharing) and try it out.

**Comment by cerberus666t** [comment]
@LeoHere Thanks it fixed the problem :)

**Comment by LeoHere** [comment]
@cerberus666t great! Thanks for letting me know. 

v1.5.5.0 is available for download. 

Closing the issue. Feel free to open it again if you need to.

**Comment by rubgithub** [comment]
Jesus! each error has one version different to fix!

1.5.3, 1.5.4, 1.5.5
